import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import Header from '../components/Header.component';
import ListOfUniversity from '../components/ListOfUniversity.component';

// import styles from '../styles/Home.module.css';

export default function Home({ allUniversities, photos }) {
  const [filteredUniversities, setFilteredUniversities] = useState([]);
  const [text, setText] = useState('');

  const searchText = (e) => {
    setText(e.target.value.toLowerCase());
  };

  useEffect(() => {
    const universities = allUniversities.filter((uni) => {
      return (
        uni['name'].toLowerCase().includes(text) ||
        uni['country'].toLowerCase().includes(text)
      );
    });
    setFilteredUniversities(universities);
  }, [allUniversities, text]);

  return (
    <div className='container'>
      <Head>
        <title>List of Universities</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header inputValue={text} onChange={searchText} />
      <ListOfUniversity universities={filteredUniversities} photos={photos} />
    </div>
  );
}

export const getStaticProps = async (ctx) => {
  let universities;
  try {
    // const response = await axios('http://localhost:5001/university');
    const response = await axios(
      'https://be-trav4college.herokuapp.com/university',
    );
    const data = response.data;
    const { universities, photos } = data;
    // console.log(data);
    // const {
    //   data: { data },
    // } = data;

    return {
      props: {
        allUniversities: universities.splice(1, 48),
        photos: photos,
      },
    };
  } catch (error) {
    // console.log(error);
    return {
      props: {
        allUniversities: [],
        photos: [],
      },
    };
  }
};
